In [2]:
import math
import numpy as np

## Sigmoid stuff

In [4]:
def basic_sigmoid(x):
    return 1/(1+math.exp(-x))
basic_sigmoid(-1)

0.2689414213699951

In [10]:
def sigmoid(x):
    return 1/(1+np.exp(-x))
x_arr = np.array([1,2,3])
sigmoid(x_arr)

array([0.73105858, 0.88079708, 0.95257413])

In [14]:
def sigmoid_derivative(x):
    return sigmoid(x)*(1-sigmoid(x))
sigmoid_derivative(x_arr)

array([0.19661193, 0.10499359, 0.04517666])

## img2vec

In [57]:
img = np.random.randint(0, 256, size=(3, 2 ,2), dtype=np.uint8)

In [60]:
def image2vector(image):
    return image.reshape(image.shape[0] * image.shape[1] * image.shape[2], 1)
image2vector(img)

array([[162],
       [ 86],
       [200],
       [ 38],
       [168],
       [ 64],
       [ 51],
       [157],
       [ 90],
       [ 75],
       [ 11],
       [ 69]], dtype=uint8)

## Normalise rows

In [63]:
def normalize_rows(x):
    abs_x = np.linalg.norm(x,axis=1,keepdims=True)
    return x/abs_x

a = np.array([[0,1000,4],[2,6,4]])
normalize_rows(a)

array([[0.        , 0.999992  , 0.00399997],
       [0.26726124, 0.80178373, 0.53452248]])

## Softmax

In [ ]:
def softmax(x):
    x = np.exp(x)
    x_sum = np.sum(x,axis=1,keepdims=True)
    return x/x_sum


## Dot Products

In [74]:
import time
n = 99999999
x1 = np.random.randn(n)
x2 = np.random.randn(n)

start = time.time()
dot_prod = 0
for i,j in zip(x1,x2):
    dot_prod += i*j
stop = time.time()

str(dot_prod),(stop-start)

('-14624.630235023547', 132.33124089241028)

####  Library implementation

In [75]:
start = time.time()
dot_prod = np.dot(x1,x2)
stop = time.time()

dot_prod,(stop - start)

(-14624.630235020797, 0.07388997077941895)